apiVersion: apps/v1
kind: Deployment
metadata:
  name: evershop-app
  labels:
    app: evershop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evershop-app
  template:
    metadata:
      labels:
        app: evershop-app
    spec:
      containers:
      - name: evershop-app-container
        image: evershop/evershop:latest
        ports:
        - containerPort: 3000
        env:
            - name: DB_HOST
              value: evershop-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_NAME
              value: postgres        

---
apiVersion: v1
kind: Service
metadata:
  name: evershop-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000